services:
  - type: web
    name: mag-player
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn mag_player.wsgi:application
    disk:
      name: media
      mountPath: /var/media
      sizeGB: 5
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: mag-ps6z.onrender.com,.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://mag-ps6z.onrender.com,https://*.onrender.com
      - key: CSRF_COOKIE_SECURE
        value: True
      - key: SESSION_COOKIE_SECURE
        value: True
      - key: SECURE_SSL_REDIRECT
        value: True
      - key: DATABASE_URL
        fromDatabase:
          name: dbmag
          property: connectionString
      - key: MEDIA_ROOT
        value: /var/media
      - key: SERVE_MEDIA
        value: True

databases:
  - name: dbmag
    databaseName: dbmag
    user: dbmag_user
