services:
  - type: web
    name: mag-player
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn mag_player.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CSRF_COOKIE_SECURE
        value: True
      - key: SESSION_COOKIE_SECURE
        value: True
